---
- hosts: localhost
  tasks:
    - name: sending mail 
      mail:
        host: "smtp.gmail.com"
        port: 587
        username: "likkivijaya07@gmail.com"
        password: "secret"
        to: likki <likkivijayalakshmi@gmail.com>
        subject: Ansible-report
        body: 'System {{ ansible_hostname }} has been successfully provisioned.'      
      delegate_to: localhost

     - name: sending mail with attachment
      mail:
        host: 127.0.0.1
        subject: Ansible-report
        body: "Hi i am sending attachment here for your reference"
        from: likkivijaya07@gmail.com (vijaya likki)
        to: 
        - likki <likkivijayalakshmi@gmail.com>
        - saideswararao <gaddamsaideswararao@gmail.com>
        cc: unknown <example@gmail.com>
        attach: /etc/file1.txt
      delegate_to: localhost

